### ISSUE TITLE
PE ratio and 52 week range?

### ISSUE THREAD

**Issue by laoshaw** [jkwill87/stonky#6]
if these two key fields are added that will be nice.

**Comment by jkwill87** [comment]
I don't think that these features would be the right fit for this project. stonky provides a snapshot of how your securities are performing for the day. Other date ranges won't make sense without getting a lot more information from the user like when they were purchased. For the same reason P/E ratios don't make sense to include for day-to-day monitoring since this isn't something that changes frequently and aren't typically part of stock ticker lines.
