### ISSUE TITLE
Improve Column Alignment

### ISSUE THREAD

**Issue by edgusp** [jkwill87/stonky#9]
The width of the columns are to small, maybe it's possible to make it dynamic?

![image](https://user-images.githubusercontent.com/70746263/98941237-8f4cf800-24ec-11eb-9ce7-97bc5b1882ab.png)

**Comment by MMartin09** [comment]
I looked into the code and you could change the code in `stock.py`in the function `ticker_tape`. There is a line with ` s = self.ticket.ljust(8)`. If you change thelength to for example 12 it should fit everything. 

Resizing it dynamically would be no problem by searching for the longest entry of the watchlist and add a constant value (for example, 3 to it). I would create a pull request but I am not sure how @jkwill87 would like to pass the value to the stock class. Maybe a new `formatter` class would be a good idea?

**Comment by jkwill87** [comment]
I agree that this could probably be improved upon. Its not just the ticket field that's a problem here either-- there's nothing stopping any of the other fields from pushing into their neighbour's columns.

I would also prefer a more dynamic solution but this would be a bit more involved. Each `Stock` is printed without the context of its neighbours. A proper solution would be to decouple the `Stock` class' model from its view and leave the responsibility of formatting elsewhere, e.g. by `StockStore` or a helper class that's a member of `StockStore` as @MMartin09 suggests. I'd be happy to review a PR for that, otherwise I'll probably get around to implementing it myself 😛 .

In the short term I could probably do a combination of increasing column padding and truncating their contents.

**Comment by jkwill87** [comment]
Should be fixed in release 1.2.2.
